name: e2e-latest-rancher
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 22 * * *
permissions: read-all
jobs:
  e2e-tests:
    uses: ./.github/workflows/e2e.yaml
    secrets:
      GKE_CREDENTIALS: ${{ secrets.GKE_CREDENTIALS }}
      GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
